### ISSUE TITLE
Why using MurmurHash instead of String.hashCode()?

### ISSUE THREAD

**Issue by tesseract2048** [xpqiu/fnlp#15]
My profiling shows String.getBytes() are quiet slow, while MurmurHash would do getBytes() every single hash because it is bytes oriented.

If the primary purpose is speeding up hashing, why not use String.hashCode() instead?

**Comment by xpqiu** [comment]
I'm heard that MurmurHash is more effective than java's original hash. Can you provide some comparison information between them?

**Comment by tesseract2048** [comment]
A large variety of factors may have influence on the general performance, such as hashing speed, collision rate, etc. 

So I would not simply perform micro-benchmark on hashing functions, but benchmark  `CWSTagger.tag2Array` instead.

## Benchmark Code

```
package org.fnlp.test;

import org.fnlp.nlp.cn.tag.CWSTagger;
import org.fnlp.util.exception.LoadModelException;

public class HashBenchmark {

    private CWSTagger cws;

    public HashBenchmark() {
        try {
            long t = System.currentTimeMillis();
            cws = new CWSTagger();
            long elapsed = System.currentTimeMillis() - t;
            System.out.println("Fnlp loaded in " + elapsed + " ms.");
        } catch (LoadModelException e) {
            throw new RuntimeException("Failed to load fnlp", e);
        }
    }

    protected String[] getCws(String text) {
        return cws.tag2Array(text);
    }

    protected void benchmark() {
        long t = System.currentTimeMillis();
        String input = "12月1日，长江经济带海关区域通关一体化改革实现流域全覆盖，南昌、武汉、长沙、成都、重庆、贵阳、昆明等7个海关加入改革。当天，流域12个关区的海关特殊监管区域也纳入区域通关一体化，长江全流域真正实现了“12关如1关”。这标志着京津冀、长江经济带、广东地区三大区域通关一体化改革全面实施";
        for (int i = 0; i < 5000; i++) {
            getCws(input);
        }
        long elapsed = System.currentTimeMillis() - t;
        System.out.println("Benchmarked " + elapsed + " ms.");
    }

    public void run() {
        // warm up the code, and perform benchmark
        for (int k = 0; k < 10; k ++) {
            benchmark();
        }
    }

    public static void main(String[] args) throws InterruptedException {
        new HashBenchmark().run();
    }
}
```

## Results:
### using `MurmurHash`
```
Fnlp loaded in 637 ms.
Benchmarked 2773 ms.
Benchmarked 1373 ms.
Benchmarked 1133 ms.
Benchmarked 1091 ms.
Benchmarked 1109 ms.
Benchmarked 1174 ms.
Benchmarked 1114 ms.
Benchmarked 1094 ms.
Benchmarked 1097 ms.
Benchmarked 1110 ms.
```

### using `String.hashCode()`
```
Fnlp loaded in 455 ms.
Benchmarked 1357 ms.
Benchmarked 1140 ms.
Benchmarked 982 ms.
Benchmarked 925 ms.
Benchmarked 940 ms.
Benchmarked 966 ms.
Benchmarked 951 ms.
Benchmarked 937 ms.
Benchmarked 936 ms.
Benchmarked 936 ms.
```

## Conclusion

Obviously, `String.hashCode()` generally perform better than `MurmurHash` in this particular scenario.

I suspect that this is because:
* `MurmurHash.hash32` function accepts `byte[]` as input, so input `String` needs to be encoded to UTF-8, which is expensive
* `MurmurHash` has better performance on longer inputs (> 100 bytes), and further reduce the collisions. But in our case, the `String`s are extremely short (i.e. `O/长/C/`, `关/区/`), and even the most stupid hashing function would rarely cause collision.

**Comment by xpqiu** [comment]
Thanks very much. Your suggestion and comparison are very valuable!  I'll do some experiments before next release.

**Comment by tesseract2048** [comment]
Hi, 

I've carried out another experiment, resulting that modified version of `MurmurHash` is indeed faster than `String.hashCode()`.

The modification is performed on `MurmurHash.hashcode` method:
```
   public int hashcode(String str) {
        int len = str.length();
        int pos = 0;
        byte[] buf = new byte[len << 1];
        for (int i = 0; i < len; i++) {
            char c = str.charAt(i);
            buf[pos++] = (byte) (c & 0xFF);
            buf[pos++] = (byte) (c >> 8);
        }
        return hash32(buf, buf.length);
    }
```

This eliminates `String.toBytes()` calls, and use hand-written encoding instead of UTF-8.
In experiment, this is nearly 33% faster than original `MurmurHash`, and nearly 20% faster than `String.hashCode()`, which suggests the second conclusion I proposed in last comment was wrong.

Perhaps this is because `String.hashCode()` generates values in a limited range for short strings, which is really "friendly" to collisions.

**Comment by xpqiu** [comment]
Great!

**Comment by mailsanchu** [comment]
for (int k = 0; k < 1000000000; k++) {
            murmurHash.hashcode(k + "");
//            (k + "").hashCode();
        }

**Comment by mailsanchu** [comment]
```
 long start = System.currentTimeMillis();
        MurmurHash murmurHash = new MurmurHash();
        for (int k = 0; k < 1000000000; k++) {
            murmurHash.hashcode(k + "");
//            (k + "").hashCode();
        }
```

**Comment by mailsanchu** [comment]
I dont think new hash code is faster though
