### ISSUE TITLE
实体识别有问题

### ISSUE THREAD

**Issue by shengxc** [xpqiu/fnlp#16]
在fnlp-demo下的org.fnlp.demo.nlp.NamedEntityRecognition类运行会报错，原因好像是在part-of-speech标注的时候会产生实体名这样的标签，但是org.fnlp.nlp.cn.PartOfSpeech枚举中没有实体名这一名字导致该类isEntiry函数出错。

**Comment by xpqiu** [comment]
请提供一下具体的错误信息：）

**Comment by shengxc** [comment]
就是demo中org.fnlp.demo.nlp.NamedEntityRecognition类本身的main函数运行就会报错

**Comment by xpqiu** [comment]
你更新下看看是否已经修正了？我本地没发现错误：）

**Comment by shengxc** [comment]
好的，请问一下FNLP中分词所用的特征是什么？我没有找到相关材料，谢谢！
