### ISSUE TITLE
english speaker

### ISSUE THREAD

**Issue by brw31415** [xpqiu/fnlp#35]
hello,

i'm a software developer in the us. i am interested in multi-lingual computer communication. chinese language would be very useful for an exploratory project, however, i don't speak chinese. could anyone there help me?  i would think someone would find this project interesting and i (potentially) have other talented collaborators (based on if they can be convinced of worthiness,  etc).

**Comment by kcheng-mvp** [comment]
May be I can help you. you can reach me by my email kcheng.mvp@gmail.com

**Comment by brw31415** [comment]
Dear Mr Cheng,

Thank you for your kind reply. I am independent developer without a lot of
resources at the moment. I am seeking assistance or partnership with
someone capable of NLP in Chinese for a chatbot systems to potentially
assist English speakers to communicate with Chinese users. I have certain
commercial applications in mind (.( ie screening help requests, product
inquiries, etc) I). The concept is that a multi-langaue chatbot could save
a lot of time communicating within a limited, highly specified domain.  I
am also casually in touch with the developers of open source of Superscript
(http://superscriptjs.com/)  through my input, is being considered
developed for language-independence. Although it is language-independent,
the internals of Superscript are in English, and Superscript is based on
the node NLP English  system (same author) already has tools that are I
think are congruent the Chinese NLP system according to your website.

If this interests you, I would be most interested. As I say, I am
independent developer, but unfortunately ignorant of Chinese language
skills, based in the US. I haven't been involved with IT for several years,
and when I left, I was doing mostly Java , so I have some catch up to do!

If you are interested in further discussion, please let me know, and we can
have a skype discussion. I will be away involved in some other things until
early next March.


Best regards,

Brian Wolf
